### ISSUE TITLE
Allow configuration of nexusUrl

### ISSUE THREAD

**Issue by jruaux** [kordamp/maven-shade-ext-transformers#3]
I'm not sure if this is where the Kordamp Gradle Plugins grab their nexus publishing configuration from, but if it is then it would be nice to expose the nexusUrl in the same way that sonatype username and password are.
The current url is "https://s01.oss.sonatype.org/service/local/" which is only for new Sonatype users.

**Comment by aalmiray** [comment]
All Gradle based Kordamp projects rely on the `kordamp-parent` plugins to configure themselves. The `org.kordamp.gradle.parent-pom` defines the base settings similarly as it's done for Maven with parent POMs.

In particular, settings for publishing to Maven Central are handled with a `stage` profile https://github.com/kordamp/kordamp-parent/blob/master/plugins/kordamp-parentpom/src/main/groovy/org/kordamp/gradle/KordampParentPomPlugin.groovy#L147-L169

If I understand you correctly, you'd want the `org.kordamp.gradle.base` to plugin to expose a property where the Sonatype URL may be set? Username/password are handled by the `config.info.credentials` DSL block https://kordamp.org/kordamp-gradle-plugins/#_base_info_credentials

**Comment by jruaux** [comment]
Great, thanks for clarifying. I'll submit a PR on kordamp-parent

**Comment by aalmiray** [comment]
Be aware that kordamp-parent defines settings specific for Kordamp projects. If you'd like the setting to be available to a broader set of projects then I'd suggest opening a ticket at kordamp/kordamp-gradle-plugins instead.
